# .github/workflows/coverage.yml
name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        
    - name: Run tests with coverage
      continue-on-error: true  # This allows the workflow to continue even if tests fail
      run: |
        tox -e py39 || true
        if [ -d "htmlcov" ]; then
          echo "Coverage report generated successfully"
        else
          echo "Coverage report generation failed"
          mkdir -p htmlcov
          echo "<html><body><h1>Coverage Report Failed</h1><p>Tests failed but workflow continued.</p></body></html>" > htmlcov/index.html
        fi
        
    - name: Deploy coverage report
      if: always()  # This ensures the step runs even if previous steps failed
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./htmlcov
        destination_dir: coverage
        force_orphan: true  # This ensures a clean publish every time

    - name: Report Status
      if: always()  # This ensures the step runs even if previous steps failed
      run: |
        if [ -f "htmlcov/index.html" ]; then
          echo "Coverage report has been generated and deployed"
          echo "View it at https://yourusername.github.io/aloof-union/coverage/"
        else
          echo "Coverage report generation failed"
        fi