# .github/workflows/coverage.yml
name: Coverage Report

# Add permissions at workflow level
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # You can also add permissions at job level if needed
    permissions:
      contents: write
      pages: write
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        
    - name: Run tests with coverage
      continue-on-error: true
      run: |
        tox -e py39 || true
        if [ -d "htmlcov" ]; then
          echo "Coverage report generated successfully"
        else
          echo "Coverage report generation failed"
          mkdir -p htmlcov
          echo "<html><body><h1>Coverage Report Failed</h1><p>Tests failed but workflow continued.</p></body></html>" > htmlcov/index.html
        fi
        
    - name: Deploy coverage report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./htmlcov
        destination_dir: coverage
        force_orphan: true

    - name: Report Status
      if: always()
      run: |
        if [ -f "htmlcov/index.html" ]; then
          echo "Coverage report has been generated and deployed"
          echo "View it at https://yourusername.github.io/aloof-union/coverage/"
        else
          echo "Coverage report generation failed"
        fi